version: '3.7'
services:
  node:
    container_name: node-prisma
    build:
      context: ./
      dockerfile: Dockerfile.node
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
  db:
    container_name: db-prisma
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "8040:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prisma
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-prisma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8042:80'